### ISSUE TITLE
ValueError: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3' Registration failed.

### ISSUE THREAD

**Issue by hdnh2006** [sergiovirahonda/FaceMaskDetectionOnPi#2]
Hi, thanks for this tutorial about yolov5 on edge.

I finally couldn't run the `detect4pi.py` because the following error:

```
(yolov5tf) pi@raspberrypi:~/Projects/FaceMaskDetection/yolov5 $ python detect4pi.py --weights customweights/best-fp16.tflite --img 416 --conf 0.45 --source "http://192.168.1.78:4747/video" --classes 0 1
Namespace(agnostic_nms=False, augment=False, cfg='./models/yolov5s.yaml', classes=[0, 1], conf_thres=0.45, device='', edgetpu=False, exist_ok=False, img_size=[416], iou_thres=0.45, name='exp', no_tf_nms=False, project='runs/detect', save_conf=False, save_txt=False, source='http://192.168.1.78:4747/video', tfl_detect=False, tfl_int8=False, update=False, view_img=False, weights=['customweights/best-fp16.tflite'])
Using torch 1.0.0a0+8322165 CPU

Traceback (most recent call last):
  File "detect4pi.py", line 270, in <module>
    detect()
  File "detect4pi.py", line 63, in detect
    interpreter = Interpreter(model_path=opt.weights[0])
  File "/home/pi/.virtualenvs/yolov5tf/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
Registration failed.

```

It seems it is something related with tflite package, any help/suggestion?

On the other hand, it seems it is not running on TPU, due the logs clearly say: `Using torch 1.0.0a0+8322165 CPU`, is this normal?

**Comment by hdnh2006** [comment]
Ok, I finally solved the problem by installing [this](tflite_runtime-2.5.0-cp37-cp37m-linux_armv7l.whl) which is done for python3.7 and raspberry. You cand find all releases [here](https://github.com/google-coral/pycoral/releases/).

Despite the use of edge TPU, It is being used, but I got another error while running `non_max_suppression`:
```
  File "/home/pi/Projects/FaceMaskDetection/yolov5/utils/general.py", line 326, in non_max_suppression
    i, j = (x[:, 5:] > conf_thres).nonzero(as_tuple=False).T
TypeError: nonzero() takes no keyword arguments
```

I will open another issue for this.

**Comment by soseazi** [comment]
> Hi, thanks for this tutorial about yolov5 on edge.
> 
> I finally couldn't run the `detect4pi.py` because the following error:
> 
> ```
> (yolov5tf) pi@raspberrypi:~/Projects/FaceMaskDetection/yolov5 $ python detect4pi.py --weights customweights/best-fp16.tflite --img 416 --conf 0.45 --source "http://192.168.1.78:4747/video" --classes 0 1
> Namespace(agnostic_nms=False, augment=False, cfg='./models/yolov5s.yaml', classes=[0, 1], conf_thres=0.45, device='', edgetpu=False, exist_ok=False, img_size=[416], iou_thres=0.45, name='exp', no_tf_nms=False, project='runs/detect', save_conf=False, save_txt=False, source='http://192.168.1.78:4747/video', tfl_detect=False, tfl_int8=False, update=False, view_img=False, weights=['customweights/best-fp16.tflite'])
> Using torch 1.0.0a0+8322165 CPU
> 
> Traceback (most recent call last):
>   File "detect4pi.py", line 270, in <module>
>     detect()
>   File "detect4pi.py", line 63, in detect
>     interpreter = Interpreter(model_path=opt.weights[0])
>   File "/home/pi/.virtualenvs/yolov5tf/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
>     model_path, self._custom_op_registerers))
> ValueError: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
> Registration failed.
> ```
> 
> It seems it is something related with tflite package, any help/suggestion?
> 
> On the other hand, it seems it is not running on TPU, due the logs clearly say: `Using torch 1.0.0a0+8322165 CPU`, is this normal?

Did you resolve the not tpu using problem?
I am also experiencing the same issue

**Comment by hdnh2006** [comment]
Hi @soseazi I didn't solve this problem. Actually, I think raspberry is not the best hardware for yolov5. In fact, in the [YOLOv5 Export Competion](https://ultralytics.com/article/export-competition-winners), Raspberry was declared as "No winner", however, Google Coral TPU had [winner](https://github.com/jveitchmichaelis/edgetpu-yolo/), so, in this case I would recommend you for check this solution due to the TPU used here by @sergiovirahonda is almost the same.

Anyway, I think @sergiovirahonda is not actually using the TPU I he doesn't explain how many fps he got, so in this case, I think he is actually using the CPU and the connection with the TPU is not done. Let's hope Sergio, repond some day about this.
